### ISSUE TITLE
Page 388 Field "No" OnValidate trigger code doesn't work

### ISSUE THREAD

**Issue by ichoosered** [PacktPublishing/Programming-Microsoft-Dynamics-365-Business-Central-Sixth-Edition#1]
Hi, i followed the book and i'm stuck on page 388 and the code doesn't compile saying:

"The name 'Type' does not exist in the current context."

I'm using latest version of business central (V11, 2023 release wave 1)

![image](https://github.com/PacktPublishing/Programming-Microsoft-Dynamics-365-Business-Central-Sixth-Edition/assets/96144435/c6c89ce8-9dc5-423d-999f-8664f647b2fa)

**Comment by ichoosered** [comment]
i think in many places in the code the keyword "rec." must be added to make it work with latest version of business central, during the course of the book i had to add this many times to be able to compile code, nowhere in the book or in the provided code there is a mention of this so i think this is a change made by Microsoft. See an example of this here: 

![image](https://github.com/PacktPublishing/Programming-Microsoft-Dynamics-365-Business-Central-Sixth-Edition/assets/96144435/785554ed-3fa6-4f73-b6f8-915626fc48d9)

If you are writing a new edition of the book you should update your code, right now the code on this repo won't compile!

**Comment by marijebrummel** [comment]
Hi, you are correct and this will be fixed in the next version that is scheduled to ship next year,

Marije
